### PR TITLE
Add Nmap Scanner Functionality

### LINKED ISSUE #21: Feature: nmap scanner to scan all the found IPs
PurplePanda should get all the public IPs found, and call nmap using some python lib and create the following relations with the output of nmap (check the relations purplepanda is already creating with shodan).

### PR DESCRIPTION
**Pull request by njmulsqb**
This is the basic functionality that finds the open ports for the public IP addresses and adds the ports to the graph DB

Here's the neo4j screenshot
image
Query: `MATCH (n:PublicIP)-[:HAS_PORT]->(m:PublicPort) RETURN n,m LIMIT 25`

fixes #21

### CODE REVIEW

**Comment by carlospolop** [comment]
Hey @njmulsqb,
It looks cool! Just a couple of other easy things to add if you don't mind:
- Could you add a new param `-n` or `--nmap` that will make nmap trigger (so it's not launched by default but only if any of those params are used)?
- Does that nmap scan scan all the ports or just the top 1000? Could you make sure the implementation will scan all the ports?
- Could you make sure this change will work in the Docker version? I guess that at least if will be needed to install nmap using the Dockerbuild

Thanks!

**Comment by njmulsqb** [comment]
Hi @carlospolop,

Yes sure, I will work on the param and port thing and will push changes on this PR.
As far as docker is concerned, I have never worked with Docker development before. Can you please guide me on it a bit more what exactly am I supposed to do so that I can learn that specific thing from internet and then try to implement it?

**Comment by carlospolop** [comment]
Thanks!
The Docker file was an easy thing, just check:  cb117e2b9123103b217ffbf5edd332407e61e850

**Comment by njmulsqb** [comment]
Done!

**Comment by carlospolop** [comment]
Thanks!

**Pull request merged**
